# Generated by Django 4.1.5 on 2023-01-18 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(blank=True, max_length=254)),
                ('department', models.CharField(blank=True, max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=254)),
                ('type', models.CharField(blank=True, max_length=254)),
                ('venue', models.CharField(blank=True, max_length=254)),
                ('date', models.DateTimeField(blank=True)),
                ('sponser', models.CharField(blank=True, max_length=254)),
                ('file', models.FileField(blank=True, upload_to='publications/')),
                ('grant', models.CharField(blank=True, max_length=254)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubs', to='publication.faculty')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('award', models.CharField(blank=True, default='', max_length=254)),
                ('patent', models.CharField(blank=True, default='', max_length=254)),
                ('institute', models.CharField(blank=True, max_length=254)),
                ('department', models.CharField(blank=True, max_length=254)),
                ('publication', models.ManyToManyField(blank=True, related_name='stupubs', to='publication.publication')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
