# Generated by Django 4.1.5 on 2023-01-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_alter_faculty_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='institute',
            new_name='institution',
        ),
    ]
