# Generated by Django 4.1.5 on 2023-01-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_rename_institute_faculty_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='institute',
            new_name='institution',
        ),
    ]
